# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\x12\x0c\x66iletransfer\"#\n\x13\x46ileDownloadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x0b\x46ileRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"-\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\xb1\x01\n\x13\x46ileTransferService\x12G\n\nUploadFile\x12\x19.filetransfer.FileRequest\x1a\x1a.filetransfer.FileResponse\"\x00(\x01\x12Q\n\x0c\x44ownloadFile\x12!.filetransfer.FileDownloadRequest\x1a\x1a.filetransfer.FileResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=37
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=72
  _globals['_FILEREQUEST']._serialized_start=74
  _globals['_FILEREQUEST']._serialized_end=115
  _globals['_FILERESPONSE']._serialized_start=117
  _globals['_FILERESPONSE']._serialized_end=162
  _globals['_FILETRANSFERSERVICE']._serialized_start=165
  _globals['_FILETRANSFERSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
