# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_transfer_pb2 as file__transfer__pb2


class FileTransferServiceStub(object):
    """The file transfer service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/filetransfer.FileTransferService/UploadFile',
                request_serializer=file__transfer__pb2.FileRequest.SerializeToString,
                response_deserializer=file__transfer__pb2.FileResponse.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/filetransfer.FileTransferService/DownloadFile',
                request_serializer=file__transfer__pb2.FileDownloadRequest.SerializeToString,
                response_deserializer=file__transfer__pb2.FileResponse.FromString,
                )


class FileTransferServiceServicer(object):
    """The file transfer service definition.
    """

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__transfer__pb2.FileRequest.FromString,
                    response_serializer=file__transfer__pb2.FileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__transfer__pb2.FileDownloadRequest.FromString,
                    response_serializer=file__transfer__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filetransfer.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """The file transfer service definition.
    """

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/filetransfer.FileTransferService/UploadFile',
            file__transfer__pb2.FileRequest.SerializeToString,
            file__transfer__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/filetransfer.FileTransferService/DownloadFile',
            file__transfer__pb2.FileDownloadRequest.SerializeToString,
            file__transfer__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
